# Generated by Django 5.2.1 on 2025-06-07 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("action", "0001_initial"),
        ("role", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="workflow.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Steps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stepName", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=256, null=True)),
                ("isInitialized", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="role.positions"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StepActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="action.actions"
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflow.steps"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StepTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "from_step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflow.steps",
                    ),
                ),
                (
                    "to_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflow.steps",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workflows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("workflowName", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=256, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("deployed", "Deployed"),
                            ("paused", "Paused"),
                            ("initialized", "Initialized"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                ("isInitialized", models.BooleanField(default=False)),
                (
                    "mainCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_workflows",
                        to="workflow.category",
                    ),
                ),
                (
                    "subCategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sub_workflows",
                        to="workflow.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="steps",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workflow.workflows"
            ),
        ),
    ]
