# Generated by Django 5.2.1 on 2025-06-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steps",
            name="position",
        ),
        migrations.RemoveField(
            model_name="steps",
            name="workflow",
        ),
        migrations.RemoveField(
            model_name="steptransition",
            name="from_step",
        ),
        migrations.RemoveField(
            model_name="steptransition",
            name="to_step",
        ),
        migrations.DeleteModel(
            name="StepActions",
        ),
        migrations.DeleteModel(
            name="Steps",
        ),
        migrations.DeleteModel(
            name="StepTransition",
        ),
    ]
