# Generated by Django 5.2.1 on 2025-06-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workflows",
            constraint=models.UniqueConstraint(
                fields=("mainCategory", "subCategory"),
                name="unique_main_sub_per_workflow",
            ),
        ),
    ]
