# Generated by Django 5.2.1 on 2025-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflows',
            name='workflow_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
