# Generated by Django 5.2.1 on 2025-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_category_parent_alter_workflows_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflows',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
