# Generated by Django 5.2.1 on 2025-06-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
