# Generated by Django 5.2.1 on 2025-06-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_ticket_id'),
        ('tickets', '0003_workflowticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['original_ticket_id'], name='tickets_wor_origina_801822_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['source_service'], name='tickets_wor_source__e71823_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['status'], name='tickets_wor_status_6eae60_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['priority'], name='tickets_wor_priorit_9c52b1_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['customer'], name='tickets_wor_custome_49d788_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowticket',
            index=models.Index(fields=['department'], name='tickets_wor_departm_e8afbb_idx'),
        ),
    ]
