# Generated by Django 5.2.1 on 2025-06-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_delete_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowticket',
            name='is_task_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
