# Generated by Django 5.2.1 on 2025-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
