# Generated by Django 5.2.1 on 2025-06-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('step', '0001_initial'),
        ('task', '0002_task_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_instance_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('user_id', models.IntegerField()),
                ('step_transition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.steptransition', to_field='transition_id', unique=True)),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task', to_field='task_id')),
            ],
        ),
    ]
