# Generated by Django 5.2.1 on 2025-06-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("role", "0001_initial"),
        ("step", "0001_initial"),
        ("task", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleRoundRobinPointer",
            fields=[
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="role.roles",
                        to_field="role_id",
                    ),
                ),
                ("pointer", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StepInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_instance_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("user_id", models.IntegerField(null=True)),
                ("has_acted", models.BooleanField(default=False)),
                (
                    "step_transition_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="step.steptransition",
                        to_field="transition_id",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.task",
                        to_field="task_id",
                    ),
                ),
            ],
        ),
    ]
