# Generated by Django 5.2.1 on 2025-06-12 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_roles_role_id'),
        ('step_instance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleRoundRobinPointer',
            fields=[
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='role.roles', to_field='role_id')),
                ('last_index', models.PositiveIntegerField(default=-1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
