# Generated by Django 5.2.1 on 2025-06-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_instance', '0002_roleroundrobinpointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepinstance',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
