# Generated by Django 5.2.1 on 2025-06-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_steptransition_workflow_id'),
        ('step_instance', '0003_alter_stepinstance_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepinstance',
            name='step_transition_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.steptransition', to_field='transition_id'),
        ),
    ]
