# Generated by Django 5.2.1 on 2025-06-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_instance', '0004_alter_stepinstance_step_transition_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepinstance',
            name='has_acted',
            field=models.BooleanField(default=False),
        ),
    ]
