# Generated by Django 5.2.1 on 2025-06-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_instance', '0005_stepinstance_has_acted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleroundrobinpointer',
            name='last_index',
        ),
        migrations.AddField(
            model_name='roleroundrobinpointer',
            name='pointer',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
