# Generated by Django 5.2.1 on 2025-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Low', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed'), ('On Hold', 'On Hold')], default='Open', max_length=20)),
                ('opened_on', models.DateField()),
                ('sla', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('original_ticket_id', models.CharField(max_length=20)),
                ('source_service', models.CharField(default='ticket_service', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_task_allocated', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['original_ticket_id'], name='tickets_wor_origina_801822_idx'), models.Index(fields=['source_service'], name='tickets_wor_source__e71823_idx'), models.Index(fields=['status'], name='tickets_wor_status_6eae60_idx'), models.Index(fields=['priority'], name='tickets_wor_priorit_9c52b1_idx'), models.Index(fields=['customer'], name='tickets_wor_custome_49d788_idx'), models.Index(fields=['department'], name='tickets_wor_departm_e8afbb_idx')],
            },
        ),
    ]
