# Generated by Django 5.2.1 on 2025-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
