# Generated by Django 5.2.1 on 2025-06-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0002_actions_action_id'),
        ('role', '0002_roles_role_id'),
        ('workflow', '0003_category_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_initialized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.roles')),
                ('workflow_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflows')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.actions', unique=True)),
                ('from_step_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='step.steps')),
                ('to_step_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='step.steps')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('action_id',), name='unique_action_per_transition')],
            },
        ),
    ]
