# Generated by Django 5.2.1 on 2025-06-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("user_id", models.IntegerField()),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=256, null=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
