# Generated by Django 5.2.1 on 2025-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_category_ticket_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
