# Generated by Django 5.2.1 on 2025-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_pushed_to_workflow_ticket_workflow_push_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketpushqueue',
            options={},
        ),
        migrations.RenameField(
            model_name='ticketpushqueue',
            old_name='error_message',
            new_name='last_error',
        ),
        migrations.RenameField(
            model_name='ticketpushqueue',
            old_name='max_attempts',
            new_name='max_retries',
        ),
        migrations.RenameField(
            model_name='ticketpushqueue',
            old_name='attempts',
            new_name='retry_count',
        ),
        migrations.RenameField(
            model_name='ticketpushqueue',
            old_name='next_retry_at',
            new_name='scheduled_for',
        ),
        migrations.AlterField(
            model_name='ticketpushqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ticketpushqueue',
            index=models.Index(fields=['status'], name='tickets_tic_status_7d678e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpushqueue',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_b48063_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpushqueue',
            index=models.Index(fields=['scheduled_for'], name='tickets_tic_schedul_f9e0b0_idx'),
        ),
    ]
