# Generated by Django 5.2.1 on 2025-06-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticketpushqueue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pushed_to_workflow',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='workflow_push_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='workflow_ticket_id',
        ),
        migrations.DeleteModel(
            name='TicketPushQueue',
        ),
    ]
