# Generated by Django 5.2.1 on 2025-06-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='role_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
