# Generated by Django 5.2.1 on 2025-06-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_roles_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='user_id',
        ),
    ]
