# Generated by Django 5.2.1 on 2025-06-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_category_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='workflow.category', to_field='category_id'),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='main_workflows', to='workflow.category', to_field='category_id'),
        ),
        migrations.AlterField(
            model_name='workflows',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='sub_workflows', to='workflow.category', to_field='category_id'),
        ),
    ]
