# Generated by Django 5.2.1 on 2025-05-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positions",
            name="description",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="positions",
            name="positionName",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
