# Generated by Django 5.2.1 on 2025-06-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("action", "0001_initial"),
        ("role", "0001_initial"),
        ("workflow", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Steps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=256, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_initialized", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="role.roles",
                        to_field="role_id",
                    ),
                ),
                (
                    "workflow_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.workflows",
                        to_field="workflow_id",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StepTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transition_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "action_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="action.actions",
                        to_field="action_id",
                        unique=True,
                    ),
                ),
                (
                    "from_step_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="step.steps",
                        to_field="step_id",
                    ),
                ),
                (
                    "to_step_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="step.steps",
                        to_field="step_id",
                    ),
                ),
                (
                    "workflow_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workflow.workflows",
                        to_field="workflow_id",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("action_id",), name="unique_action_per_step_transition"
                    )
                ],
            },
        ),
    ]
