# Generated by Django 5.2.1 on 2025-06-10 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_actions_action_id'),
        ('role', '0002_roles_role_id'),
        ('step', '0001_initial'),
        ('workflow', '0004_alter_category_parent_alter_workflows_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('workflow_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deployed', 'Deployed'), ('paused', 'Paused'), ('initialized', 'Initialized')], default='draft', max_length=16)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='steptransition',
            name='unique_action_per_transition',
        ),
        migrations.AddField(
            model_name='steps',
            name='step_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='steptransition',
            name='transition_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='steps',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='role.roles', to_field='role_id'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='workflow_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.workflows', to_field='workflow_id'),
        ),
        migrations.AlterField(
            model_name='steptransition',
            name='action_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.actions', to_field='action_id', unique=True),
        ),
        migrations.AlterField(
            model_name='steptransition',
            name='from_step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='step.steps', to_field='step_id'),
        ),
        migrations.AlterField(
            model_name='steptransition',
            name='to_step_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='step.steps', to_field='step_id'),
        ),
        migrations.AddConstraint(
            model_name='steptransition',
            constraint=models.UniqueConstraint(fields=('action_id',), name='unique_action_per_step_transition'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='step.category', to_field='category_id'),
        ),
        migrations.AddField(
            model_name='workflows',
            name='category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.PROTECT, related_name='main_workflows', to='step.category', to_field='category_id'),
        ),
        migrations.AddField(
            model_name='workflows',
            name='sub_category',
            field=models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.PROTECT, related_name='sub_workflows', to='step.category', to_field='category_id'),
        ),
        migrations.AddConstraint(
            model_name='workflows',
            constraint=models.UniqueConstraint(fields=('category', 'sub_category'), name='unique_category_subcategory_per_workflow'),
        ),
    ]
