# Generated by Django 5.2.1 on 2025-06-08 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptransition',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.actions', unique=True),
        ),
    ]
