# Generated by Django 5.2.1 on 2025-06-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_steptransition_workflow_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steptransition',
            name='workflow_id',
        ),
    ]
