# Generated by Django 5.2.1 on 2025-06-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_remove_steptransition_workflow_id'),
        ('workflow', '0005_workflows_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptransition',
            name='workflow_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflow.workflows', to_field='workflow_id'),
        ),
    ]
