# Generated by Django 5.2.1 on 2025-06-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
