# Generated by Django 5.2.1 on 2025-06-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_task_description_task_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
