# Generated by Django 5.2.1 on 2025-06-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_created_at_remove_task_updated_at'),
        ('tickets', '0003_workflowticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ticket_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.workflowticket'),
        ),
    ]
