# Generated by Django 5.2.1 on 2025-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workflows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField()),
                ("workflowName", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(max_length=256, null=True)),
                ("mainCategory", models.CharField(max_length=64)),
                ("subCategory", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
