# Generated by Django 5.2.1 on 2025-05-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("action", "0001_initial"),
        ("workflow", "0002_steps"),
    ]

    operations = [
        migrations.CreateModel(
            name="StepActions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="action.actions"
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="workflow.steps"
                    ),
                ),
            ],
        ),
    ]
