# Generated by Django 5.2.1 on 2025-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_stepactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflows',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deployed', 'Deployed'), ('paused', 'Paused')], default='draft', max_length=16),
        ),
    ]
