# Generated by Django 5.2.1 on 2025-05-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflows_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='isInitialized',
            field=models.BooleanField(default=False),
        ),
    ]
