# Generated by Django 5.2.1 on 2025-05-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_steps_isinitialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflows',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('deployed', 'Deployed'), ('paused', 'Paused'), ('initialized', 'Initialized')], default='draft', max_length=16),
        ),
    ]
