# Generated by Django 5.2 on 2025-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0006_alter_workflows_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflows",
            name="isInitialized",
            field=models.BooleanField(default=False),
        ),
    ]
