# Generated by Django 5.2.1 on 2025-06-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0007_workflows_isinitialized"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="steps",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="steps",
            name="next_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_steps",
                to="workflow.steps",
            ),
        ),
        migrations.AddField(
            model_name="steps",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
