# Generated by Django 5.2.1 on 2025-06-03 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0008_alter_steps_options_steps_next_step_steps_order"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="steps",
            unique_together={("workflow", "order")},
        ),
        migrations.AddField(
            model_name="steps",
            name="next_steps",
            field=models.ManyToManyField(
                blank=True, related_name="previous_steps", to="workflow.steps"
            ),
        ),
        migrations.AlterField(
            model_name="steps",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="workflow.workflows",
            ),
        ),
        migrations.RemoveField(
            model_name="steps",
            name="next_step",
        ),
    ]
