# Generated by Django 5.2.1 on 2025-06-03 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0009_alter_steps_unique_together_steps_next_steps_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="steps",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="steps",
            name="next_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_steps",
                to="workflow.steps",
            ),
        ),
        migrations.AlterField(
            model_name="steps",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="workflow.workflows"
            ),
        ),
        migrations.RemoveField(
            model_name="steps",
            name="next_steps",
        ),
    ]
