# Generated by Django 5.2.1 on 2025-06-04 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0010_alter_steps_unique_together_steps_next_step_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steps",
            name="next_step",
        ),
        migrations.CreateModel(
            name="StepTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("condition", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "from_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transitions",
                        to="workflow.steps",
                    ),
                ),
                (
                    "to_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transitions",
                        to="workflow.steps",
                    ),
                ),
            ],
        ),
    ]
