# Generated by Django 5.2.1 on 2025-06-04 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0011_remove_steps_next_step_steptransition"),
    ]

    operations = [
        migrations.AddField(
            model_name="steps",
            name="next_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_steps",
                to="workflow.steps",
            ),
        ),
    ]
