# Generated by Django 5.2.1 on 2025-06-04 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_steps_next_step"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="steps",
            name="next_step",
        ),
    ]
