# Generated by Django 5.2.1 on 2025-06-04 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0013_remove_steps_next_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="steptransition",
            name="from_step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_transitions",
                to="workflow.steps",
            ),
        ),
    ]
