# Generated by Django 5.2.1 on 2025-06-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0014_alter_steptransition_from_step"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="workflow.category",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="workflows",
            name="mainCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="main_workflows",
                to="workflow.category",
            ),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="subCategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_workflows",
                to="workflow.category",
            ),
        ),
    ]
