# Generated by Django 5.2 on 2025-05-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('historylogId', models.AutoField(primary_key=True, serialize=False)),
                ('taskId', models.IntegerField()),
                ('agentId', models.IntegerField()),
                ('action', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
