name: Deploy frontend

on:
  push:
    branches:
      - PreProduction
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Dummy step to pass validation
        run: echo "Frontend build job initialized"
