name: Deploy Service 1 to Azure WebApp

on:
  push:
    branches:
      - PreProduction
    paths:
      - 'user_service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test

      - name: Run migrations
        run: python manage.py migrate

      - name: Archive app for deployment
        run: zip -r release.zip .
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: user_service/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6DFBD1F1466E4084813043F7889E4ABC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8CF76D579C4840819931324120911D4E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FA8FB51F8FE14B2C8B4191144FC16F7C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ttsuserservices'
          slot-name: 'Production'
          package: .
