# Generated by Django 5.2.1 on 2025-06-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("action", "0001_initial"),
        ("step_instance", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_log_id",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "action_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="action.actions",
                        to_field="action_id",
                        unique=True,
                    ),
                ),
                (
                    "step_instance_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="step_instance.stepinstance",
                        to_field="step_instance_id",
                    ),
                ),
            ],
        ),
    ]
