# Generated by Django 5.2.1 on 2025-06-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action', '0002_actions_action_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_log_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('action_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='action.actions', to_field='action_id', unique=True)),
            ],
        ),
    ]
