# Generated by Django 5.2.1 on 2025-06-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('action_log', '0001_initial'),
        ('step_instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='step_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step_instance.stepinstance', to_field='step_instance_id'),
        ),
    ]
